// FILENAME:	DM_Bloody_Brunch.cs
//
// AUTHORS:  	Chupie Doll & Youth in Asia
//------------------------------------------------------------------------------

exec("multiplayerStdLib.cs");
exec("DMstdLib.cs");

$missionName = "Wilzuun_Demo_Map";
exec(ShapeStdLib);

function setRules()
{
    %rules = "<jc><f2>Welcome to the Demo Map!<f0>\n<b0,5:table_head8.bmp><b0,5:table_head8.bmp><jl>\n\n<y17>This map will show off the functions of the scripts that ^TFW^WIlzuun has made." @
		"\nEach orb will find on the map after spawning will spawn different shapes, or objects, or start simple mission objectives for ease of use, and ease of example usage.";
    setGameInfo(%rules);
}

function setDefaultMissionOptions()
{
	$server::TeamPlay = false;
	$server::AllowDeathmatch = true;
	$server::AllowTeamPlay = true;	
	
	$server::AllowTeamRed = true;
	$server::AllowTeamBlue = true;
	$server::AllowTeamYellow = true;
	$server::AllowTeamPurple = true;
}

function onMissionStart()
{
	venusSounds();
    makeObjectArray();
	GetNewShape();
}

function onMissionLoad(){
   cdAudioCycle("Watching", "Cyberntx", "Cloudburst"); 
}

function Welcome::structure::onscan(%scanned,%scanner) {
	say(0,0,"Welcome to the Demo Map of WIlzuun's Scripts.");
}
// Each Orb creates a different shape when scanned. The shapes maybe rotated, set off from 0,0 or elevated off
// the ground.

	// $radius is how far from center of the circle to the edge of the circle.
$radius = 400;
	// the Offset variables move the circle around the map. zOffset is related to the terrain where the object will be spawned. (In these examples, zOffset is set to 1)
$xOffset = -100;
$yOffset = -800;
$zOffset = 1;
	// $circleCount is how many points on the circle do you want marked. The more there are, the slower the spawn rate of the items.
$circleCount = 36;
$distance = 100;
	// $object is any object file name with out the file extension.
$object = xbridgehub4;
    // Rotation of the shape.
$rotation = 90;

function Circle::structure::onscan(%scanned,%scanner) {
	CleanAllShapes();
	// shape - itemCount, Radius, xOffset, yOffset, zOffset, plane
	// For the circle creation function, these are the things that are required.
	// The last parameter is what plane the circle is on. xy is horizontal. xz and yz each face either north/south, or west/east. (Appearing as a flat line when looked at from their opposing direction.)
	Shape::Circle ($object, $circleCount, $radius, $xOffset, $yoffset, 1, xy);
}
function sphere::structure::onscan(%scanned,%scanner) {
	CleanAllShapes();
	// %Shape, %radius, %xOffset, %yOffset, %zOffset, %vSpawn (How many rings... this one is hard to explain, test it.), %hSpawn (Same as a Circle's itemCount)
    // the second $circleCount is how a hSpawn couint. It determins how many "rings" to make.
	Shape::Sphere($object, $circleCount, $radius, $xOffset, $yoffset, $zOffset, $circleCount);
}
function ThreeSided::structure::onscan(%scanned,%scanner) {
	CleanAllShapes();
	// %object, %sideCount, %radius, %distance (Distance between Shapes on each side.), %xOffset, %yOffest, %zOffset, %RotationOfShape (Rotates the shape by this many degrees)
	Shape::Polygon($object, 3, $radius, $distance, $xOffset       , $yoffset, $zOffset,   $rotation);
	//Shape::Polygon($object, 3, $radius, $distance, $xOffset + 500 , $yoffset, $zOffset,  ($rotation + 45));
	$Shape::zCenter     = false;
	Shape::Polygon($object, 3, $radius, $distance, $xOffset + 1000, $yoffset, $zOffset, -($rotation + 45));
	$Shape::zCenter     = true;
}
function FourSided::structure::onscan(%scanned,%scanner) {
	CleanAllShapes();

	for(%plane = 0; %plane<5; %plane++)
		Shape::Polygon($object, 4, $radius, $distance, $xOffset + (500 * %i), $yoffset, $zOffset, $rotation + 45, %plane);
}
function FiveSided::structure::onscan(%scanned,%scanner) {
	CleanAllShapes();
	Shape::Polygon($object, 5, $radius*5, $distance, $xOffset, $yoffset, $zOffset, $rotation);
	Shape::Star($object, 5, $radius*5, $distance, $xOffset, $yoffset, $zOffset, $rotation);
}
function SixSided::structure::onscan(%scanned,%scanner) {
	CleanAllShapes();
	Shape::Polygon($object, 6, $radius, $distance, $xOffset, $yoffset, $zOffset, $rotation);
}
function SevenSided::structure::onscan(%scanned,%scanner) {
	CleanAllShapes();
	// Shape::Polygon($object, 7, $radius, $distance, $xOffset, $yoffset, $zOffset, $rotation);
	Shape::Polygon($object, 9, 4000, 100, $xOffset, $yoffset, $zOffset, $rotation);
}

function CleanAllShapes() {
	for(%i = 0; %i <=10; %i++) {
		shape::Cleanup("TheShape", %i);
	}
}

function AdjustmentOrb::structure::onscan(%this, $that)
{
	%oldShape = $object;
	GetNewShape();
	say(0, 0, "Changing obect used to make shapes from '" @ %oldShape @ "' to '" @ $object @ "'.");
}

function GetNewShape()
{
	$shapeToUse++;
	$object = $objectArray[$shapeToUse];
}

function makeObjectArray()
{
	%int = -1;
	$objectArray[%i++] = cBomberbay;
	$objectArray[%i++] = cComm;
	$objectArray[%i++] = cDropPod;
	$objectArray[%i++] = cEntrance;
	$objectArray[%i++] = cGenerator;
	$objectArray[%i++] = cMotionDetector;
	$objectArray[%i++] = cNexus;
	$objectArray[%i++] = cPerimeter;
	$objectArray[%i++] = cPower;
	$objectArray[%i++] = cRelay;
	$objectArray[%i++] = cSearchArray;
	$objectArray[%i++] = cStorage;
	$objectArray[%i++] = cTracking;
	$objectArray[%i++] = cUplink;
	$objectArray[%i++] = cWall;
	$objectArray[%i++] = cTempleWall;
	$objectArray[%i++] = cTemple;
	$objectArray[%i++] = cBeacon;
	$objectArray[%i++] = clandpad;
	$objectArray[%i++] = cbrid_p1;
	$objectArray[%i++] = cPromBase;
	$objectArray[%i++] = cbrid_p2;
	$objectArray[%i++] = csilo;
	$objectArray[%i++] = csilo_p1;
	$objectArray[%i++] = cbrid;
	$objectArray[%i++] = cbig1;
	$objectArray[%i++] = hDesertBigDish;
	$objectArray[%i++] = hDesertchurch;
	$objectArray[%i++] = hDesertDefense;
	$objectArray[%i++] = hDesertdwelling;
	$objectArray[%i++] = hDesertgarage;
	$objectArray[%i++] = hDesertgathering;
	$objectArray[%i++] = hDesertMine;
	$objectArray[%i++] = hDesertpower;
	$objectArray[%i++] = hDesertsilo;
	$objectArray[%i++] = hDesertsludge;
	$objectArray[%i++] = hDesertuplink;
	$objectArray[%i++] = hDesertvapor;
	$objectArray[%i++] = hDesertWaterTower;
	$objectArray[%i++] = hDesertTroopBarracks;
	$objectArray[%i++] = hDesertSmallTroopBarracks;
	$objectArray[%i++] = hDesertSmallTroopCom;
	$objectArray[%i++] = hDesertTroopGarage;
	$objectArray[%i++] = hDesertTroopHall;
	$objectArray[%i++] = hDesertSmallTroopHQ;
	$objectArray[%i++] = hdesertpillar_1;
	$objectArray[%i++] = hdesertpillar_2;
	$objectArray[%i++] = hdesertpillar_3;
	$objectArray[%i++] = hdesertpillar_4;
	$objectArray[%i++] = hdesertpillar_5_tall;
	$objectArray[%i++] = hdesertpillar_6_tall;
	$objectArray[%i++] = hdesertpillar_altar;
	$objectArray[%i++] = hdesertpillar_hall;
	$objectArray[%i++] = hpyramid;
	$objectArray[%i++] = hpyramid2;
	$objectArray[%i++] = hpyramid3;
	$objectArray[%i++] = hbigsand1d;
	$objectArray[%i++] = hbigsand2d;
	$objectArray[%i++] = hbigsand3d;
	$objectArray[%i++] = hbigsand4d;
	$objectArray[%i++] = hbigsand5d;
	$objectArray[%i++] = hbigsand6d;
	$objectArray[%i++] = hruinsd1;
	$objectArray[%i++] = hruinsd2;
	$objectArray[%i++] = hruinsd3;
	$objectArray[%i++] = hruinsd4;
	$objectArray[%i++] = hTroopbarracks;
	$objectArray[%i++] = hTroopbarrackssm;
	$objectArray[%i++] = hTroopbigdish;
	$objectArray[%i++] = hTroopcomm;
	$objectArray[%i++] = htroop_orbital_power;
	$objectArray[%i++] = hTroopgarage;
	$objectArray[%i++] = hTroopgaragesm;
	$objectArray[%i++] = hTroopgenerator;
	$objectArray[%i++] = hTroophall;
	$objectArray[%i++] = hTroophq;
	$objectArray[%i++] = hTrooplisten;
	$objectArray[%i++] = hTrooppower;
	$objectArray[%i++] = hTroopsupply;
	$objectArray[%i++] = hTroop_supply_dump;
	$objectArray[%i++] = hTrooptrackbase;
	$objectArray[%i++] = hTrooptrackdish;
	$objectArray[%i++] = hTroopuplink;
	$objectArray[%i++] = hTroopPlanetDefense;
	$objectArray[%i++] = hbridgee;
	$objectArray[%i++] = hgaragee;
	$objectArray[%i++] = hlandpade;
	$objectArray[%i++] = hlandpade_p1;
	$objectArray[%i++] = hhangare;
	$objectArray[%i++] = hhangare_p1;
	$objectArray[%i++] = hairporte;
	$objectArray[%i++] = hairporte_p1;
	$objectArray[%i++] = hwallhuge;
	$objectArray[%i++] = xeuroparock02;
	$objectArray[%i++] = xeuroparock03;
	$objectArray[%i++] = hheale;
	$objectArray[%i++] = hammoe;
	$objectArray[%i++] = hTroophouseE;
	$objectArray[%i++] = hRuinsT;
	$objectArray[%i++] = hRuinsT2;
	$objectArray[%i++] = hRuinsT3;
	$objectArray[%i++] = hOffice;
	$objectArray[%i++] = hSolarStation;
	$objectArray[%i++] = hSnowGathering;
	$objectArray[%i++] = hSnowlland;
	$objectArray[%i++] = hSnowChurch;
	$objectArray[%i++] = hSnowCom;
	$objectArray[%i++] = hSnowResidence;
	$objectArray[%i++] = hSnowStorage;
	$objectArray[%i++] = hSnowUplink;
	$objectArray[%i++] = xSnowRock1;
	$objectArray[%i++] = xSnowRock2;
	$objectArray[%i++] = xSnowRock3;
	$objectArray[%i++] = xTree;
	$objectArray[%i++] = xSnowMan;
	$objectArray[%i++] = hairporta;
	$objectArray[%i++] = hgatea;
	$objectArray[%i++] = hlandpada;
	$objectArray[%i++] = hpadofficea;
	$objectArray[%i++] = hheal2a;
	$objectArray[%i++] = hammo2a;
	$objectArray[%i++] = hheal2a;
	$objectArray[%i++] = hammo2a;
	$objectArray[%i++] = hAtmos;
	$objectArray[%i++] = hMarsBarracks;
	$objectArray[%i++] = hCrane;
	$objectArray[%i++] = hMarsCivGarage;
	$objectArray[%i++] = hMarsCommTower;
	$objectArray[%i++] = hMarsFarmHouse;
	$objectArray[%i++] = hFertillizer;
	$objectArray[%i++] = hMarsFusionReactor;
	$objectArray[%i++] = hGarage;
	$objectArray[%i++] = hMarsHanger;
	$objectArray[%i++] = hMarsMine;
	$objectArray[%i++] = hMarsMassDriver;
	$objectArray[%i++] = hMeethall;
	$objectArray[%i++] = hMarsMineTrain;
	$objectArray[%i++] = hMarsMineTrain_cargo;
	$objectArray[%i++] = xMonument;
	$objectArray[%i++] = hPerimeter;
	$objectArray[%i++] = hMarsPiledriver;
	$objectArray[%i++] = xMarsFlag_Police;
	$objectArray[%i++] = hPolicefin;
	$objectArray[%i++] = hPolicehq;
	$objectArray[%i++] = hPowerfin;
	$objectArray[%i++] = xMarsFlag_Rebel;
	$objectArray[%i++] = hRefinery;
	$objectArray[%i++] = hMarsResidentialBig;
	$objectArray[%i++] = hMarsResidentialSmall;
	$objectArray[%i++] = hMarsResidentialSmall_NODOOR;
	$objectArray[%i++] = hMarsStreetlight;
	$objectArray[%i++] = hMarsSupplyDump;
	$objectArray[%i++] = hTracking;
	$objectArray[%i++] = hMarsWaterTower;
	$objectArray[%i++] = hMarsWaterConverter;
	$objectArray[%i++] = hUplink;
	$objectArray[%i++] = hWall;
	$objectArray[%i++] = hMarsBigWall_1;
	$objectArray[%i++] = hMarsBigWall_2;
	$objectArray[%i++] = hMarsBigWall_3;
	$objectArray[%i++] = xMarsrock1;
	$objectArray[%i++] = xMarsrock2;
	$objectArray[%i++] = xMarsrock3;
	$objectArray[%i++] = hbridge2m;
	$objectArray[%i++] = hbridgem;
	$objectArray[%i++] = hbridgepostm;
	$objectArray[%i++] = hgaragem;
	$objectArray[%i++] = hhangarm;
	$objectArray[%i++] = hLandPadM;
	$objectArray[%i++] = hLandPad2M;
	$objectArray[%i++] = hmassplatm;
	$objectArray[%i++] = hplatformm;
	$objectArray[%i++] = hquarrym;
	$objectArray[%i++] = hheal2m;
	$objectArray[%i++] = hammo2m;
	$objectArray[%i++] = hfertruinm;
	$objectArray[%i++] = hfertruin2m;
	$objectArray[%i++] = hfertruin3m;
	$objectArray[%i++] = hRuinsM;
	$objectArray[%i++] = hRuinsM2;
	$objectArray[%i++] = hRuinsM3;
	$objectArray[%i++] = hRuinsM4;
	$objectArray[%i++] = hRuinsM6;
	$objectArray[%i++] = hbighousem;
	$objectArray[%i++] = hbighumpm;
	$objectArray[%i++] = hbighouse2m;
	$objectArray[%i++] = hBigGullym;
	$objectArray[%i++] = hBigCargom;
	$objectArray[%i++] = hbigwall1m;
	$objectArray[%i++] = hBigAmmo;
	$objectArray[%i++] = hBigHealing;
	$objectArray[%i++] = hbigmolem;
	$objectArray[%i++] = hbigmars1m;
	$objectArray[%i++] = hbigmars2m;
	$objectArray[%i++] = hbigmars3m;
	$objectArray[%i++] = hbigmars4m;
	$objectArray[%i++] = hbigmars5m;
	$objectArray[%i++] = hbigmars6m;
	$objectArray[%i++] = hbigmars2mruin;
	$objectArray[%i++] = hbigmars3mruin;
	$objectArray[%i++] = hMercuryMine;
	$objectArray[%i++] = xmercuryrock01;
	$objectArray[%i++] = xmercuryrock02;
	$objectArray[%i++] = xmercuryrock03;
	$objectArray[%i++] = hMoonbarracks;
	$objectArray[%i++] = hMoonbigdish;
	$objectArray[%i++] = hMoongather;
	$objectArray[%i++] = hMoongenerator;
	$objectArray[%i++] = hMoonlisten;
	$objectArray[%i++] = hMoonpower;
	$objectArray[%i++] = hMoonrefinery;
	$objectArray[%i++] = hMoonresidence;
	$objectArray[%i++] = hMoonsilos;
	$objectArray[%i++] = hMoonuplink;
	$objectArray[%i++] = hMoonwall;
	$objectArray[%i++] = hMoonwallcap;
	$objectArray[%i++] = hMoonwalldoor;
	$objectArray[%i++] = hMoonPlanetDefense;
	$objectArray[%i++] = hMoontroopercom;
	$objectArray[%i++] = hMoontrooperhq;
	$objectArray[%i++] = hMoontroopersilos;
	$objectArray[%i++] = hMoontrooperstorage;
	$objectArray[%i++] = hMoontrooptracking;
	$objectArray[%i++] = hlandpadl;
	$objectArray[%i++] = hminel;
	$objectArray[%i++] = hmineliftl;
	$objectArray[%i++] = hsilol;
	$objectArray[%i++] = hlunaport;
	$objectArray[%i++] = hbigluna1;
	$objectArray[%i++] = hbigluna2;
	$objectArray[%i++] = hbigluna3;
	$objectArray[%i++] = hbigluna4;
	$objectArray[%i++] = hbigluna5;
	$objectArray[%i++] = hbigluna6;
	$objectArray[%i++] = xmoonrock01;
	$objectArray[%i++] = xmoonrock02;
	$objectArray[%i++] = xmoonrock03;
	$objectArray[%i++] = xApollo;
	$objectArray[%i++] = xMoonflag;
	$objectArray[%i++] = xplutorock01;
	$objectArray[%i++] = xplutorock02;
	$objectArray[%i++] = xplutorock03;
	$objectArray[%i++] = hKongcivil;
	$objectArray[%i++] = hKonggate;
	$objectArray[%i++] = hKonggathering;
	$objectArray[%i++] = hKonghouse;
	$objectArray[%i++] = hKongdeckhouse;
	$objectArray[%i++] = hKongoffice;
	$objectArray[%i++] = hKongpagoda;
	$objectArray[%i++] = hKongsludge;
	$objectArray[%i++] = hKongtemple;
	$objectArray[%i++] = hKonglgtemple;
	$objectArray[%i++] = hHongTemple;
	$objectArray[%i++] = hkongheal;
	$objectArray[%i++] = hkongammo;
	$objectArray[%i++] = hbigkong1t;
	$objectArray[%i++] = hbigkong2t;
	$objectArray[%i++] = hbigkong3t;
	$objectArray[%i++] = hbigkong4t;
	$objectArray[%i++] = hbigkong5t;
	$objectArray[%i++] = hbigkong6t;
	$objectArray[%i++] = hbigkong7t;
	$objectArray[%i++] = hkonghide;
	$objectArray[%i++] = hkonghide2;
	$objectArray[%i++] = xtitanrock01;
	$objectArray[%i++] = xtitanrock02;
	$objectArray[%i++] = xtitanrock03;
	$objectArray[%i++] = hTitanbigdish;
	$objectArray[%i++] = hTitangather;
	$objectArray[%i++] = hTitanlisten;
	$objectArray[%i++] = hTitanpower;
	$objectArray[%i++] = hTitanMicrowave;
	$objectArray[%i++] = hTitanrefinery;
	$objectArray[%i++] = hTitanresidence;
	$objectArray[%i++] = hTitansilos;
	$objectArray[%i++] = hTitanuplink;
	$objectArray[%i++] = hTitanwall;
	$objectArray[%i++] = hTitanwallcap;
	$objectArray[%i++] = hTitanwalldoor;
	$objectArray[%i++] = hTitantroopercom;
	$objectArray[%i++] = hTitancommand;
	$objectArray[%i++] = hTitantrooperhq;
	$objectArray[%i++] = hTitantrooperresidence;
	$objectArray[%i++] = hTitantroopsilos;
	$objectArray[%i++] = hTitanBEAM;
	$objectArray[%i++] = hTitanDiasIrae;
	$objectArray[%i++] = hhealt;
	$objectArray[%i++] = hammot;
	$objectArray[%i++] = hTroophouseE;
	$objectArray[%i++] = hVenusarray;
	$objectArray[%i++] = hVenusArbor;
	$objectArray[%i++] = hVenusbigdish;
	$objectArray[%i++] = hVenuscom;
	$objectArray[%i++] = hVenusconverter1;
	$objectArray[%i++] = hVenusconverter2;
	$objectArray[%i++] = hVenusconverter3;
	$objectArray[%i++] = hVenusdispertion;
	$objectArray[%i++] = hVenusdrill;
	$objectArray[%i++] = hVenusEternalFlame;
	$objectArray[%i++] = hVenusgarage;
	$objectArray[%i++] = hVenusgathering;
	$objectArray[%i++] = hVenusgeotherm;
	$objectArray[%i++] = hVenuslightrod;
	$objectArray[%i++] = hVenuslistening;
	$objectArray[%i++] = hVenusMicrowave;
	$objectArray[%i++] = hVenusperimwall;
	$objectArray[%i++] = hVenusrefinery;
	$objectArray[%i++] = hVenussmgarage;
	$objectArray[%i++] = hVenussmwall;
	$objectArray[%i++] = hVenusstorage;
	$objectArray[%i++] = hVenustrhq;
	$objectArray[%i++] = hVenustrlink;
	$objectArray[%i++] = xvenusrock01;
	$objectArray[%i++] = xvenusrock02;
	$objectArray[%i++] = xvenusrock03;
	$objectArray[%i++] = hbridgev;
	$objectArray[%i++] = hconv;
	$objectArray[%i++] = hsmlbridgev;
	$objectArray[%i++] = hsmliftv;
	$objectArray[%i++] = hsmloilv;
	$objectArray[%i++] = hlandpadv;
	$objectArray[%i++] = hlgliftv;
	$objectArray[%i++] = hlgoilv;
	$objectArray[%i++] = hmidoilv;
	$objectArray[%i++] = hhubv;
	$objectArray[%i++] = hhealv;
	$objectArray[%i++] = hammov;
	$objectArray[%i++] = hmonumentv;
	$objectArray[%i++] = xBoxes;
	$objectArray[%i++] = xContainer;
	$objectArray[%i++] = xFuelTank;
	$objectArray[%i++] = hDropPod;
	$objectArray[%i++] = xMonument;
	$objectArray[%i++] = xobstacle;
	$objectArray[%i++] = xtroopercontainer;
	$objectArray[%i++] = xbridgehub;
	$objectArray[%i++] = xbridgehub2;
	$objectArray[%i++] = xbridgehub3;
	$objectArray[%i++] = xbridgehub4;
	$objectArray[%i++] = team1;
	$objectArray[%i++] = team2;
	$objectArray[%i++] = team3;
	$objectArray[%i++] = team4;
	$objectArray[%i++] = xCryodoor;
	$objectArray[%i++] = hmovie;
	$objectArray[%i++] = hhugescraper1;
	$objectArray[%i++] = hhugescraper2;
	$objectArray[%i++] = hhugescraper3;
	$objectArray[%i++] = hhugescraper4;
	$objectArray[%i++] = hhugescraper5;
	$objectArray[%i++] = hhugescraper6;
	$objectArray[%i++] = hhugescraper7;
	$objectArray[%i++] = hhugescraper8;
	$objectArray[%i++] = xheal_lite;
	$objectArray[%i++] = xheal_dark;
	$objectArray[%i++] = xheal_venus;
	$objectArray[%i++] = xammo_lite;
	$objectArray[%i++] = xammo_dark;
	$objectArray[%i++] = xammo_venus;
	$objectArray[%i++] = xzen_lite;
	$objectArray[%i++] = xzen_dark;
	$objectArray[%i++] = hHeallite;
	$objectArray[%i++] = hHealdark;
	$objectArray[%i++] = hHealvenus;
	$objectArray[%i++] = hAmmolite;
	$objectArray[%i++] = hAmmodark;
	$objectArray[%i++] = hAmmovenus;
	$objectArray[%i++] = hZenlite;
	$objectArray[%i++] = hZendark;
	$objectArray[%i++] = xMonument_LOW;
	$objectArray[%i++] = football;
	$objectArray[%i++] = teleport;
	$objectArray[%i++] = fx_tele_t;
	$objectArray[%i++] = cy_spac;
	$objectArray[%i++] = cin_cyspac;
	$objectArray[%i++] = cin_cyspacsm;
	$objectArray[%i++] = cin_caanon;
	$objectArray[%i++] = tr_spac;
	$objectArray[%i++] = cin_spac;
	$objectArray[%i++] = cin_earth;
	$objectArray[%i++] = cin_moon;
	$objectArray[%i++] = cin_mars;
	$objectArray[%i++] = cin_titan;
	$objectArray[%i++] = cin_saturn;
	$objectArray[%i++] = cin_pluto;
	$objectArray[%i++] = cin_merc;
	$objectArray[%i++] = cin_venus;
	$objectArray[%i++] = cin_mine;
	$objectArray[%i++] = mwarehouse;
	$objectArray[%i++] = cin_bans;
	$objectArray[%i++] = cin_cryo;
	$objectArray[%i++] = cin_escape;
	$objectArray[%i++] = cin_fire;
	$objectArray[%i++] = cin_beam;
	$objectArray[%i++] = cin_astro1;
	$objectArray[%i++] = cin_drop;
	$objectArray[%i++] = cin_drop1;
	$objectArray[%i++] = cin_drop2;
	$objectArray[%i++] = cin_drop3;
	$objectArray[%i++] = xTree;
	$objectArray[%i++] = xtree02;
	$objectArray[%i++] = xtree03;
	$objectArray[%i++] = xtree04;
	$objectArray[%i++] = xTree1;
	$objectArray[%i++] = xTree2;
	$objectArray[%i++] = xTree3;
	$objectArray[%i++] = xsnowtree;
	$objectArray[%i++] = xsnowtreetwo;
	$objectArray[%i++] = cin_baslempty;
	$objectArray[%i++] = cin_baslhb;
	$objectArray[%i++] = cin_baslhb2;
	$objectArray[%i++] = cin_cydrop;
	$objectArray[%i++] = cin_cydrop2;
	$objectArray[%i++] = cy_pod;
	$objectArray[%i++] = fx_bans_exh;
	$objectArray[%i++] = fx_bans_exhT;
	$objectArray[%i++] = fx_CARG_EXH;
	$objectArray[%i++] = fx_CARG_EXH_T;
	$objectArray[%i++] = fx_conv_exh;
	$objectArray[%i++] = fx_conv_exhT;
	$objectArray[%i++] = fx_cydrop_exh;
	$objectArray[%i++] = fx_cydrop_exhT;
	$objectArray[%i++] = fx_cypod;
	$objectArray[%i++] = fx_cypodT;
	$objectArray[%i++] = fx_cypod_far;
	$objectArray[%i++] = fx_cypod_farT;
	$objectArray[%i++] = fx_dropT;
	$objectArray[%i++] = fx_drop_exh;
	$objectArray[%i++] = fx_drop_exhT;
	$objectArray[%i++] = fx_dust;
	$objectArray[%i++] = fx_dust_bl;
	$objectArray[%i++] = fx_dust_br;
	$objectArray[%i++] = fx_dust_dbr;
	$objectArray[%i++] = fx_dust_dor;
	$objectArray[%i++] = fx_dust_dyl;
	$objectArray[%i++] = fx_dust_gr;
	$objectArray[%i++] = fx_dust_lbl;
	$objectArray[%i++] = fx_dust_lgr;
	$objectArray[%i++] = fx_dust_or;
	$objectArray[%i++] = fx_dust_yl;
	$objectArray[%i++] = fx_elec;
	$objectArray[%i++] = fx_elec_T;
	$objectArray[%i++] = fx_ESCAPE_EXH;
	$objectArray[%i++] = fx_ESCAPE_EXH_T;
	$objectArray[%i++] = fx_exhaust;
	$objectArray[%i++] = fx_exp_lg;
	$objectArray[%i++] = fx_exp_lgT;
	$objectArray[%i++] = fx_exp_md;
	$objectArray[%i++] = fx_exp_mdT;
	$objectArray[%i++] = fx_exp_pod;
	$objectArray[%i++] = fx_exp_podT;
	$objectArray[%i++] = fx_exp_sm;
	$objectArray[%i++] = fx_exp_smT;
	$objectArray[%i++] = fx_fball_md;
	$objectArray[%i++] = fx_fball_mdT;
	$objectArray[%i++] = fx_fball_sm;
	$objectArray[%i++] = fx_fball_smT;
	$objectArray[%i++] = fx_flame_lg;
	$objectArray[%i++] = fx_flame_lgT;
	$objectArray[%i++] = fx_flame_md;
	$objectArray[%i++] = fx_flame_mdT;
	$objectArray[%i++] = fx_flame_sm;
	$objectArray[%i++] = fx_flame_smT;
	$objectArray[%i++] = fx_imp_fb;
	$objectArray[%i++] = fx_imp_fbT;
	$objectArray[%i++] = fx_imp_md;
	$objectArray[%i++] = fx_imp_mdT;
	$objectArray[%i++] = fx_imp_sm;
	$objectArray[%i++] = fx_imp_smT;
	$objectArray[%i++] = fx_imp_sp;
	$objectArray[%i++] = fx_imp_spT;
	$objectArray[%i++] = fx_imp_tn;
	$objectArray[%i++] = fx_imp_tnT;
	$objectArray[%i++] = fx_orbeam;
	$objectArray[%i++] = fx_shield_elc;
	$objectArray[%i++] = fx_shield_elcT;
	$objectArray[%i++] = fx_shield_eng;
	$objectArray[%i++] = fx_shield_engT;
	$objectArray[%i++] = fx_shield_exp;
	$objectArray[%i++] = fx_shield_expT;
	$objectArray[%i++] = fx_shield_lsr;
	$objectArray[%i++] = fx_shield_lsrT;
	$objectArray[%i++] = fx_shield_ssr;
	$objectArray[%i++] = fx_shield_ssrT;
	$objectArray[%i++] = fx_shock_lg;
	$objectArray[%i++] = fx_shock_lgT;
	$objectArray[%i++] = fx_shock_md;
	$objectArray[%i++] = fx_shock_mdT;
	$objectArray[%i++] = fx_shock_sm;
	$objectArray[%i++] = fx_shock_smT;
	$objectArray[%i++] = fx_smoke_lg;
	$objectArray[%i++] = fx_smoke_lgT;
	$objectArray[%i++] = fx_smoke_md;
	$objectArray[%i++] = fx_smoke_mdT;
	$objectArray[%i++] = fx_smoke_sm;
	$objectArray[%i++] = fx_smoke_smT;
	$objectArray[%i++] = fx_smoke_tr;
	$objectArray[%i++] = fx_smoke_trT;
	$objectArray[%i++] = fx_Tele_T;
	$objectArray[%i++] = fx_thump_T;
	$objectArray[%i++] = mz_atc;
	$objectArray[%i++] = mz_atcT;
	$objectArray[%i++] = mz_blas;
	$objectArray[%i++] = mz_blasT;
	$objectArray[%i++] = mz_blnk;
	$objectArray[%i++] = mz_blnkT;
	$objectArray[%i++] = mz_clas;
	$objectArray[%i++] = mz_clasT;
	$objectArray[%i++] = mz_dis;
	$objectArray[%i++] = mz_disT;
	$objectArray[%i++] = mz_elf;
	$objectArray[%i++] = mz_elfT;
	$objectArray[%i++] = mz_emp;
	$objectArray[%i++] = mz_empT;
	$objectArray[%i++] = mz_hatc;
	$objectArray[%i++] = mz_hatcT;
	$objectArray[%i++] = mz_hbla;
	$objectArray[%i++] = mz_hblaT;
	$objectArray[%i++] = mz_las;
	$objectArray[%i++] = mz_lasT;
	$objectArray[%i++] = mz_mfac;
	$objectArray[%i++] = mz_mfacT;
	$objectArray[%i++] = mz_pbw;
	$objectArray[%i++] = mz_pbwT;
	$objectArray[%i++] = mz_plas;
	$objectArray[%i++] = mz_plasT;
	$objectArray[%i++] = mz_rail;
	$objectArray[%i++] = mz_railT;
	$objectArray[%i++] = mz_smok;
	$objectArray[%i++] = mz_smokT;
	$objectArray[%i++] = mz_tlas;
	$objectArray[%i++] = mz_tlas;
	$objectArray[%i++] = pr_ara;
	$objectArray[%i++] = pr_atc;
	$objectArray[%i++] = pr_atcT;
	$objectArray[%i++] = pr_bc;
	$objectArray[%i++] = pr_bcT;
	$objectArray[%i++] = pr_blas;
	$objectArray[%i++] = pr_blasT;
	$objectArray[%i++] = pr_blnk;
	$objectArray[%i++] = pr_blnkT;
	$objectArray[%i++] = pr_bull;
	$objectArray[%i++] = pr_bullT;
	$objectArray[%i++] = pr_dis;
	$objectArray[%i++] = pr_disT;
	$objectArray[%i++] = pr_emc;
	$objectArray[%i++] = pr_emcT;
	$objectArray[%i++] = pr_emp;
	$objectArray[%i++] = pr_empT ;
	$objectArray[%i++] = pr_hatc;
	$objectArray[%i++] = pr_hatcT;
	$objectArray[%i++] = pr_hbc;
	$objectArray[%i++] = pr_hbcT;
	$objectArray[%i++] = pr_hbla;
	$objectArray[%i++] = pr_hblaT;
	$objectArray[%i++] = pr_hshell;
	$objectArray[%i++] = pr_hshellT;
	$objectArray[%i++] = pr_mfac;
	$objectArray[%i++] = pr_mfacT;
	$objectArray[%i++] = pr_min;
	$objectArray[%i++] = pr_minT;
	$objectArray[%i++] = pr_misl1;
	$objectArray[%i++] = pr_misl1T;
	$objectArray[%i++] = pr_nano;
	$objectArray[%i++] = pr_nanoT;
	$objectArray[%i++] = pr_proj1;
	$objectArray[%i++] = pr_proj1T;
	$objectArray[%i++] = pr_proj2;
	$objectArray[%i++] = pr_proj2T;
	$objectArray[%i++] = pr_prx;
	$objectArray[%i++] = pr_rail;
	$objectArray[%i++] = pr_railT;
	$objectArray[%i++] = pr_shell;
	$objectArray[%i++] = pr_shellT;
	$objectArray[%i++] = pr_shrk;
	$objectArray[%i++] = pr_shrkT;
	$objectArray[%i++] = pr_spr;
	$objectArray[%i++] = pr_sprT;
	$objectArray[%i++] = pr_swrm;
	$objectArray[%i++] = pr_swrmT;
	$objectArray[%i++] = pr_vip;
	$objectArray[%i++] = pr_vipT;
	$objectArray[%i++] = flame;
	$objectArray[%i++] = xBlastdoor;
	$objectArray[%i++] = xBlastdoor_Anim;
	$objectArray[%i++] = xnavPoint;
	$objectArray[%i++] = xsplash;
	$objectArray[%i++] = hcryo;
	$objectArray[%i++] = wc_ARTL;
	$objectArray[%i++] = wc_blnk;
	$objectArray[%i++] = wc_emc;
	$objectArray[%i++] = wc_nano;
	$objectArray[%i++] = wc_pbw;
	$objectArray[%i++] = wc_rad;
	$objectArray[%i++] = wc_rail;
	$objectArray[%i++] = wc_shrk;
	$objectArray[%i++] = wc_tlas;
	$objectArray[%i++] = wg_atc;
	$objectArray[%i++] = wg_bc;
	$objectArray[%i++] = wg_emp;
	$objectArray[%i++] = wg_hatc;
	$objectArray[%i++] = wg_hbc;
	$objectArray[%i++] = wg_hlas;
	$objectArray[%i++] = wg_las;
	$objectArray[%i++] = wg_min;
	$objectArray[%i++] = wg_plas;
	$objectArray[%i++] = wg_spr10;
	$objectArray[%i++] = wg_spr6;
	$objectArray[%i++] = wg_vip12;
	$objectArray[%i++] = wg_vip8;
	$objectArray[%i++] = wm_blas;
	$objectArray[%i++] = wm_hbla;
	$objectArray[%i++] = wm_mfac;
	$objectArray[%i++] = wm_ncan;
	$objectArray[%i++] = wm_qgun;
	$objectArray[%i++] = wm_sgun;
	$objectArray[%i++] = wr_ARTL;
	$objectArray[%i++] = wt_clas;
	$objectArray[%i++] = wt_dis;
	$objectArray[%i++] = wt_elf;
	$objectArray[%i++] = wt_nike;
	$objectArray[%i++] = wt_supr;
	$objectArray[%i++] = wt_swrm;
	$objectArray[%i++] = wx_ARTL;
	$objectArray[%i++] = wx_can;
	$objectArray[%i++] = wx_gat;
	$objectArray[%i++] = wx_gun;
	$objectArray[%i++] = wx_TURM;
	$objectArray[%i++] = cLaserGun;
	$objectArray[%i++] = cLaserTurret;
	$objectArray[%i++] = cMissleTurret;
	$objectArray[%i++] = hCannon;
	$objectArray[%i++] = hDesertCannon;
	$objectArray[%i++] = hDesertLaserShort;
	$objectArray[%i++] = hDesertLaserTall;
	$objectArray[%i++] = hDesertMissleShort;
	$objectArray[%i++] = hDesertMissleTall;
	$objectArray[%i++] = hEarthLaserShort;
	$objectArray[%i++] = hEarthLaserTall;
	$objectArray[%i++] = hEarthMissleShort;
	$objectArray[%i++] = hEarthMissleTall;
	$objectArray[%i++] = hMarsLaserShort;
	$objectArray[%i++] = hMarsLaserTall;
	$objectArray[%i++] = hMarsMissleShort;
	$objectArray[%i++] = hMarsMissleTall;
	$objectArray[%i++] = hMoonLaserShort;
	$objectArray[%i++] = hMoonLaserTall;
	$objectArray[%i++] = hMoonMissleShort;
	$objectArray[%i++] = hMoonMissleTall;
	$objectArray[%i++] = hTitanLaserShort;
	$objectArray[%i++] = hTitanLaserTall;
	$objectArray[%i++] = hTitanMissleShort;
	$objectArray[%i++] = hTitanMissleTall;
	$objectArray[%i++] = hVenusLaserShort;
	$objectArray[%i++] = hVenusLaserTall;
	$objectArray[%i++] = hVenusMissleShort;
	$objectArray[%i++] = hVenusMissleTall;
	$objectArray[%i++] = "2m_cyln";
	$objectArray[%i++] = "2m_PYRM";
	$objectArray[%i++] = cube2;
	$objectArray[%i++] = arrow5_y;
	$objectArray[%i++] = arrow5_b;
	$objectArray[%i++] = arrow5_r;
	$objectArray[%i++] = arrow5_g;
	$objectArray[%i++] = arrow5;
	$objectArray[%i++] = arrow25;
	$objectArray[%i++] = arrow50;
	$objectArray[%i++] = DEBRIS_LRG_1;
	$objectArray[%i++] = DEBRIS_LRG_2;
	$objectArray[%i++] = DEBRIS_LRG_3;
	$objectArray[%i++] = DEBRIS_LRG_4;
	$objectArray[%i++] = DEBRIS_MAN;
	$objectArray[%i++] = DEBRIS_MED_1;
	$objectArray[%i++] = DEBRIS_MED_2;
	$objectArray[%i++] = DEBRIS_MED_3;
	$objectArray[%i++] = DEBRIS_MED_4;
	$objectArray[%i++] = DEBRIS_PAN_1;
	$objectArray[%i++] = DEBRIS_PAN_2;
	$objectArray[%i++] = DEBRIS_PAN_3;
	$objectArray[%i++] = DEBRIS_SML_1;
	$objectArray[%i++] = DEBRIS_SML_2;
	$objectArray[%i++] = DEBRIS_SML_3;
	$objectArray[%i++] = DEBRIS_XLRG_1;
	$objectArray[%i++] = DEBRIS_XLRG_2;
	$objectArray[%i++] = DEBRIS_XLRG_3;
	$objectArray[%i++] = hulk_10X10;
	$objectArray[%i++] = hulk_10X20;
	$objectArray[%i++] = hulk_20X30;
	$objectArray[%i++] = hulk_20X40;
	$objectArray[%i++] = hulk_40X40;
	$objectArray[%i++] = hulk_45X30;
	$objectArray[%i++] = hulk_4X5;
	$objectArray[%i++] = ca_BASL;
	$objectArray[%i++] = cin_APOC;
	$objectArray[%i++] = cin_basl;
	$objectArray[%i++] = cy_ADVO;
	$objectArray[%i++] = cy_ARTL;
	$objectArray[%i++] = cy_bolo;
	$objectArray[%i++] = cy_cons;
	$objectArray[%i++] = cy_drop;
	$objectArray[%i++] = cy_EXEC;
	$objectArray[%i++] = cy_GOAD;
	$objectArray[%i++] = cy_JAMM;
	$objectArray[%i++] = cy_JUDG;
	$objectArray[%i++] = cy_OMNI;
	$objectArray[%i++] = cy_PROM;
	$objectArray[%i++] = cy_PROT;
	$objectArray[%i++] = cy_RECL;
	$objectArray[%i++] = cy_SEEK;
	$objectArray[%i++] = cy_SHEP;
	$objectArray[%i++] = ha_APOC;
	$objectArray[%i++] = ha_PRED;
	$objectArray[%i++] = kn_APOC;
	$objectArray[%i++] = kn_BANS;
	$objectArray[%i++] = kn_BASL;
	$objectArray[%i++] = kn_DISR;
	$objectArray[%i++] = kn_drop;
	$objectArray[%i++] = kn_GORG;
	$objectArray[%i++] = kn_MINO;
	$objectArray[%i++] = kn_MYRM;
	$objectArray[%i++] = kn_PALA;
	$objectArray[%i++] = kn_talon;
	$objectArray[%i++] = mg_EXEC;
	$objectArray[%i++] = mg_GOAD;
	$objectArray[%i++] = mg_JUDG;
	$objectArray[%i++] = mg_SEEK;
	$objectArray[%i++] = mg_SHEP;
	$objectArray[%i++] = pi_apoc;
	$objectArray[%i++] = pi_drea;
	$objectArray[%i++] = pi_eman;
	$objectArray[%i++] = pl_EXEC;
	$objectArray[%i++] = pl_JUDG;
	$objectArray[%i++] = rb_ARTL;
	$objectArray[%i++] = rb_AVEN;
	$objectArray[%i++] = rb_BIKE;
	$objectArray[%i++] = rb_DREA;
	$objectArray[%i++] = rb_EMAN;
	$objectArray[%i++] = rb_FLTB;
	$objectArray[%i++] = rb_FLTB_AMMO;
	$objectArray[%i++] = rb_FLTB_BIG;
	$objectArray[%i++] = rb_FLTB_BIG_AMMO;
	$objectArray[%i++] = rb_FLTB_BIG_BOX;
	$objectArray[%i++] = rb_FLTB_BOX;
	$objectArray[%i++] = rb_OLY;
	$objectArray[%i++] = rb_THUM;
	$objectArray[%i++] = ss_bus;
	$objectArray[%i++] = tr_APOC;
	$objectArray[%i++] = tr_BANS;
	$objectArray[%i++] = tr_BASL;
	$objectArray[%i++] = TR_CARG;
	$objectArray[%i++] = tr_conv;
	$objectArray[%i++] = tr_DISR;
	$objectArray[%i++] = tr_drac;
	$objectArray[%i++] = tr_drop;
	$objectArray[%i++] = TR_ESCAPE;
	$objectArray[%i++] = TR_FLTB;
	$objectArray[%i++] = TR_FLTB_AMMO;
	$objectArray[%i++] = TR_FLTB_BIG_AMMO;
	$objectArray[%i++] = TR_FLTB_BIG_PERSONEL;
	$objectArray[%i++] = TR_FLTB_FUEL;
	$objectArray[%i++] = TR_FLTB_MINO;
	$objectArray[%i++] = tr_GORG;
	$objectArray[%i++] = tr_MINO;
	$objectArray[%i++] = tr_MYRM;
	$objectArray[%i++] = tr_NIKE;
	$objectArray[%i++] = tr_PALA;
	$objectArray[%i++] = tr_SOVE;
	$objectArray[%i++] = tr_STAR;
	$objectArray[%i++] = tr_SUPR;
	$objectArray[%i++] = tr_SURV;
	$objectArray[%i++] = tr_talon;
	$objectArray[%i++] = TR_UTIL;
	$objectArray[%i++] = redbeam;
	$objectArray[%i++] = orangebeam;
	$objectArray[%i++] = yellowbeam;
	$objectArray[%i++] = greenbeam;
	$objectArray[%i++] = bluebeam;
	$objectArray[%i++] = purplebeam;
	$objectArray[%i++] = pinkbeam;
	$objectArray[%i++] = whitebeam;
}